### ISSUE TITLE
Todo list of version 1.0

### ISSUE THREAD

**Issue by creeperyang** [creeperyang/sugar-cli#23]
- [x] Fix bugs wont fix with `0.x`, like build error (concurrently render templates will lead to uncorrect token's template url).
- [x] Use `sugar-template@1.x`.
- [x] Cache control with LRU cache.
- [x] Rewrite cli command, like use `verbose` instead of `silent`, remove unused cmd, split args which can be used with cli and which should in `config.js`.
- [x] Use default `sugar.config.js`. 

All done with https://github.com/creeperyang/sugar-cli/pull/24
